In [1]:
# NumPy is already installed in Google Colab

import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


Question 1: What is NumPy?
Definition

NumPy (Numerical Python) is a Python library used for fast numerical computing. It provides a powerful N-dimensional array (ndarray) and many built-in mathematical functions.

It is one of the most important libraries in Python and is widely used in:

Data Science
Machine Learning
Artificial Intelligence
Deep Learning
Scientific Computing
Image Processing
Data Analysis
Why do we use NumPy?

Python lists are good for storing data, but they become slow when working with large datasets.

NumPy solves this by:

Performing calculations much faster.
Using less memory.
Supporting multidimensional arrays.
Providing optimized mathematical functions.

In [3]:
import numpy as np

marks = np.array([75, 80, 92, 68, 88])

print("Marks:", marks)
print("Average:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Marks: [75 80 92 68 88]
Average: 80.6
Maximum: 92
Minimum: 68


Question 2. Why is NumPy faster than Python Lists?
First Understand Python List

Python List

[10,20,30,40]

Each element is stored separately in memory.

Different data types can exist together.

[10,"Hello",3.5,True]

This flexibility makes lists slower.

NumPy Array
[10 20 30 40]

Stores all values in one continuous block of memory.

All elements have the same data type.

This allows the CPU to process them much faster.

In [4]:
import numpy as np
import time

# Python List
lst = list(range(1000000))

start = time.time()

lst = [x*2 for x in lst]

print("Python List Time:", time.time()-start)

# NumPy Array

arr = np.arange(1000000)

start = time.time()

arr = arr*2

print("NumPy Time:", time.time()-start)

Python List Time: 0.15639591217041016
NumPy Time: 0.012059211730957031


Question 3. What is an ndarray?

ndarray means N-Dimensional Array.

It is the main data structure of NumPy.

It can store:

1D arrays
2D arrays
3D arrays
Higher-dimensional arrays

In [5]:
#1D Array
import numpy as np

a = np.array([1,2,3])

print(a)

[1 2 3]


In [6]:
#2D Array
b = np.array([
    [1,2],
    [3,4]
])

print(b)

[[1 2]
 [3 4]]


In [7]:
#3D Array
c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Question 4. Difference Between Python List and NumPy

In [8]:
#Python List
a = [1,2,3]

print(a*2)

[1, 2, 3, 1, 2, 3]


In [9]:
#Numpy
import numpy as np

a = np.array([1,2,3])

print(a*2)

[2 4 6]


Question 5. How do you create a NumPy array?

In [10]:
#Method 1
import numpy as np

arr = np.array([1,2,3,4])

print(arr)

[1 2 3 4]


In [12]:
#Method 2
#2D Array

arr = np.array([
    [1,2],
    [3,4]
])

print(arr)

[[1 2]
 [3 4]]


In [13]:
#Method 3
#Float Array

arr = np.array([1.2,2.3,3.4])

print(arr)

[1.2 2.3 3.4]


In [14]:
#Method 4
#String Array

arr = np.array(["Apple","Banana"])

print(arr)

['Apple' 'Banana']


Question 6. Difference Between np.arange() and np.linspace()

In [15]:
#np.arrange
import numpy as np

a = np.arange(0,10,2)

print(a)

[0 2 4 6 8]


In [16]:
#np.linespace
b = np.linspace(0,10,5)

print(b)

[ 0.   2.5  5.   7.5 10. ]


Question 7. Different Ways to Initialize Arrays

In [17]:
#Zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#Ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#Empty
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#Indentity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#Full
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

Question 8. Check Shape, Size, Dimensions and Data Type

In [25]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr.shape

(2, 3)

In [26]:
arr.size

6

In [27]:
arr.ndim

2

In [28]:
arr.dtype

dtype('int64')

Question 9. What are NumPy Data Types (dtype)?

dtype tells you what type of data is stored in the array.

In [29]:
arr = np.array([1,2,3], dtype=float)

print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


Question 10. How do you change the data type?

In [30]:
#Use astype()
import numpy as np

arr = np.array([1,2,3])

new_arr = arr.astype(float)

print(new_arr)
print(new_arr.dtype)

[1. 2. 3.]
float64
