In [ ]:
# NumPy is already installed in Google Colab

import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


Question 1: What is NumPy?
Definition

NumPy (Numerical Python) is a Python library used for fast numerical computing. It provides a powerful N-dimensional array (ndarray) and many built-in mathematical functions.

It is one of the most important libraries in Python and is widely used in:

Data Science
Machine Learning
Artificial Intelligence
Deep Learning
Scientific Computing
Image Processing
Data Analysis
Why do we use NumPy?

Python lists are good for storing data, but they become slow when working with large datasets.

NumPy solves this by:

Performing calculations much faster.
Using less memory.
Supporting multidimensional arrays.
Providing optimized mathematical functions.

In [ ]:
import numpy as np

marks = np.array([75, 80, 92, 68, 88])

print("Marks:", marks)
print("Average:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Marks: [75 80 92 68 88]
Average: 80.6
Maximum: 92
Minimum: 68


Question 2. Why is NumPy faster than Python Lists?
First Understand Python List

Python List

[10,20,30,40]

Each element is stored separately in memory.

Different data types can exist together.

[10,"Hello",3.5,True]

This flexibility makes lists slower.

NumPy Array
[10 20 30 40]

Stores all values in one continuous block of memory.

All elements have the same data type.

This allows the CPU to process them much faster.

In [ ]:
import numpy as np
import time

# Python List
lst = list(range(1000000))

start = time.time()

lst = [x*2 for x in lst]

print("Python List Time:", time.time()-start)

# NumPy Array

arr = np.arange(1000000)

start = time.time()

arr = arr*2

print("NumPy Time:", time.time()-start)

Python List Time: 0.15639591217041016
NumPy Time: 0.012059211730957031


Question 3. What is an ndarray?

ndarray means N-Dimensional Array.

It is the main data structure of NumPy.

It can store:

1D arrays
2D arrays
3D arrays
Higher-dimensional arrays

In [ ]:
#1D Array
import numpy as np

a = np.array([1,2,3])

print(a)

[1 2 3]


In [ ]:
#2D Array
b = np.array([
    [1,2],
    [3,4]
])

print(b)

[[1 2]
 [3 4]]


In [ ]:
#3D Array
c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Question 4. Difference Between Python List and NumPy

In [ ]:
#Python List
a = [1,2,3]

print(a*2)

[1, 2, 3, 1, 2, 3]


In [ ]:
#Numpy
import numpy as np

a = np.array([1,2,3])

print(a*2)

[2 4 6]


Question 5. How do you create a NumPy array?

In [ ]:
#Method 1
import numpy as np

arr = np.array([1,2,3,4])

print(arr)

[1 2 3 4]


In [ ]:
#Method 2
#2D Array

arr = np.array([
    [1,2],
    [3,4]
])

print(arr)

[[1 2]
 [3 4]]


In [ ]:
#Method 3
#Float Array

arr = np.array([1.2,2.3,3.4])

print(arr)

[1.2 2.3 3.4]


In [ ]:
#Method 4
#String Array

arr = np.array(["Apple","Banana"])

print(arr)

['Apple' 'Banana']


Question 6. Difference Between np.arange() and np.linspace()

In [ ]:
#np.arrange
import numpy as np

a = np.arange(0,10,2)

print(a)

[0 2 4 6 8]


In [ ]:
#np.linespace
b = np.linspace(0,10,5)

print(b)

[ 0.   2.5  5.   7.5 10. ]


Question 7. Different Ways to Initialize Arrays

In [ ]:
#Zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Empty
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Indentity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Full
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

Question 8. Check Shape, Size, Dimensions and Data Type

In [ ]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.ndim

2

In [ ]:
arr.dtype

dtype('int64')

Question 9. What are NumPy Data Types (dtype)?

dtype tells you what type of data is stored in the array.

In [ ]:
arr = np.array([1,2,3], dtype=float)

print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


Question 10. How do you change the data type?

In [ ]:
#Use astype()
import numpy as np

arr = np.array([1,2,3])

new_arr = arr.astype(float)

print(new_arr)
print(new_arr.dtype)

[1. 2. 3.]
float64


In [ ]:
import numpy as np

Question 11. What is Array Indexing?
Easy Explanation

Imagine an array is like a row of boxes.

Index:  0   1   2   3   4
Value: [5, 10, 15, 20, 25]

Each element has an index (position).

We use the index to access a value.

In [ ]:
import numpy as np

arr = np.array([5,10,15,20,25])

print(arr[0])

5


In [ ]:
print(arr[2])

15


In [ ]:
#2D Array Indexing
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr[1,2])

60


Question 12. What is Slicing?

Slicing means taking a portion of an array.

In [ ]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4])

[20 30 40]


In [ ]:
#skip values
print(arr[::2])

[10 30 50]


In [ ]:
#Reverse array
print(arr[::-1])

[60 50 40 30 20 10]


In [ ]:
#2D Slicing
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[0:2,1:3])

[[2 3]
 [5 6]]


Question 13. What is Boolean Indexing?

Boolean indexing filters elements based on a condition.

In [ ]:
arr = np.array([45,80,90,30,75])

print(arr[arr>50])

[80 90 75]


In [ ]:
#Even Number
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[arr%2==0])

[2 4 6 8]


In [ ]:
#Odd Number
print(arr[arr%2!=0])

[1 3 5 7]


Question 14. What is Fancy Indexing?|

Fancy indexing means selecting elements using a list or array of indices.

In [ ]:
arr=np.array([10,20,30,40,50])

print(arr[[0,2,4]])

[10 30 50]


In [ ]:
#2D Example
arr=np.array([
    [10,20],
    [30,40],
    [50,60]
])

print(arr[[0,2]])


[[10 20]
 [50 60]]


Question 15. What is Broadcasting?

Broadcasting means NumPy automatically expands smaller arrays to perform operations with larger arrays.

In [ ]:
arr=np.array([1,2,3])

print(arr+5)

[6 7 8]


In [ ]:
#2D Example
arr=np.array([
    [1,2],
    [3,4]
])

print(arr+10)


[[11 12]
 [13 14]]


Question 16. Broadcasting Rules

NumPy compares dimensions from right to left.

Two dimensions are compatible if:

They are equal.
One of them is 1.

Otherwise, broadcasting fails.

In [ ]:
#Example works
a=np.array([[1],[2],[3]])

b=np.array([10,20,30])

print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
#Example error
a=np.array([1,2])

b=np.array([1,2,3])

print(a+b)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

Question 17. What is Vectorization?
Easy Explanation

Vectorization means performing operations on an entire array at once instead of using loops.

In [ ]:
#Without Vectorization
numbers=[1,2,3,4]

result=[]

for i in numbers:
    result.append(i*2)

print(result)

[2, 4, 6, 8]


In [ ]:
#With Vectorization
arr=np.array([1,2,3,4])

print(arr*2)

[2 4 6 8]


Question 18. Difference Between reshape() and resize()

In [ ]:
#reshape()
arr=np.arange(6)

new_arr=arr.reshape(2,3)

print(new_arr)

[[0 1 2]
 [3 4 5]]


In [ ]:
#resize()
arr=np.array([1,2,3,4])

arr.resize((2,2))

print(arr)

[[1 2]
 [3 4]]


Question 19. Difference Between flatten() and ravel()

In [ ]:
arr=np.array([
    [1,2],
    [3,4]
])

In [ ]:
#flatten
new_arr=arr.flatten()


In [ ]:
#ravel()
new_arr=arr.ravel()

In [ ]:
arr=np.array([[1,2],[3,4]])

new=arr.ravel()

new[0]=100

print(arr)

[[100   2]
 [  3   4]]


Question 20. Difference Between View and Copy
View

A view shares memory with the original array.

Changing one affects the other.

A copy creates a completely new array.

In [ ]:
arr=np.array([1,2,3])

view=arr.view()

view[0]=100

print(arr)

[100   2   3]


In [ ]:
#copy
arr=np.array([1,2,3])

copy=arr.copy()

copy[0]=100

print(arr)

[1 2 3]


In [ ]:
import numpy as np

print("NumPy is ready!")

NumPy is ready!


21. How do you concatenate multiple arrays?

Concatenation means joining arrays together.

In [ ]:
#1D Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))

print(result)

[1 2 3 4 5 6]


In [ ]:
#2D Array
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.concatenate((a, b))

print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


22. How do you split an array?

Splitting is the opposite idea of concatenation.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

result = np.split(arr, 3)

print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#split into 2
arr = np.array([10, 20, 30, 40])

a, b = np.split(arr, 2)

print(a)
print(b)

[10 20]
[30 40]


In [ ]:
#2D example
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

result = np.split(arr, 2)

print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


23. What are Universal Functions (ufuncs)?

This is an important interview question.

A ufunc means Universal Function.

These functions operate element-by-element on NumPy arrays.

In [ ]:
arr = np.array([1, 4, 9])

In [ ]:
print(np.sqrt(arr))

[1. 2. 3.]


In [ ]:
#square root
np.sqrt(arr)

array([1., 2., 3.])

In [ ]:
#exponential
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [ ]:
#absolute value
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [ ]:
#sin
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849])

In [ ]:
#cos
np.cos(arr)

array([ 0.54030231, -0.65364362, -0.91113026])

24. What is the purpose of the axis parameter?

In [5]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

#axis=0
print(np.sum(arr, axis=0))

[50 70 90]


In [6]:
#axis=1
print(np.sum(arr, axis=1))

[ 60 150]


25. Difference between axis=0 and axis=1

In [7]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.sum(axis=0))

[5 7 9]


In [8]:
axis=1
print(arr.sum(axis=1))

[ 6 15]


26. Element-wise multiplication vs Matrix multiplication

In [10]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

A * B

array([[ 5, 12],
       [21, 32]])

In [11]:
#Matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

27. Difference between np.dot(), @, and np.matmul()

In [12]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [13]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [14]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(np.dot(A, B))
print(A @ B)
print(np.matmul(A, B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


28. How do you generate random numbers?

In [15]:
#random number
print(np.random.rand())

0.7646149100615367


In [16]:
#random array
arr = np.random.rand(2, 3)

print(arr)

[[0.89745494 0.51647042 0.73722339]
 [0.54634114 0.08100904 0.08458001]]


In [17]:
#random integer
arr = np.random.randint(1, 10, size=5)

print(arr)

[8 2 7 4 3]


29. How do you find unique values, counts and frequencies?

In [19]:
arr = np.array([10,20,10,30,20,10,40])
print(np.unique(arr))

[10 20 30 40]


In [20]:
values, counts = np.unique(arr, return_counts=True)

print(values)
print(counts)

[10 20 30 40]
[3 2 1 1]


30. Best Practices for Optimizing NumPy Performance

In [21]:
#1.use vectorization
result = arr * 2

In [22]:
#2.avoid unnecessary loops
arr = arr * 2

In [23]:
#3.use appropriate data types
arr = np.array([1,2,3], dtype=np.int32)

In [24]:
#4.avoid unnecessary copies
view = arr.view()

In [25]:
#5.use numpy function
total = np.sum(arr)

In [26]:
#6.Preallocate arrays when appropriate
result = np.zeros(1000)

In [27]:
#8.Use efficient NumPy operations
arr.sum()

np.int64(6)